### ISSUE TITLE
ps runtime error :bad magic number. what is the dev python version?

### ISSUE THREAD

**Issue by buyvtuygJW** [vaibhavnayel/Audio-to-MIDI-converter#1]
Thank you very much

**Comment by buyvtuygJW** [comment]
btw, how to us this big boi,no arguments so runtime console input?it ends silently though

**Comment by buyvtuygJW** [comment]
if use test.py **python test.py
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    data=np.average(data,axis=1)
  File "<__array_function__ internals>", line 6, in average
  File "E:\Coding\PYFastCache\PYVenv\Venv37_gpuacc\lib\site-packages\numpy\lib\function_base.py", line 390, in average
    avg = a.mean(axis)
  File "E:\Coding\PYFastCache\PYVenv\Venv37_gpuacc\lib\site-packages\numpy\core\_methods.py", line 138, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "E:\Coding\PYFastCache\PYVenv\Venv37_gpuacc\lib\site-packages\numpy\core\_methods.py", line 57, in _count_reduce_items
    items *= arr.shape[ax]
IndexError: tuple index out of range**

**Comment by FrankJY** [comment]
same error
